onnx/models

README.md
Describe how to use the serialized TensorProto for test purpose.
=> Add description of how to use serialized TensorProto as test data

bvlc_alexnet/LICENSE, bvlc_alexnet/README.md, bvlc_googlenet/LICENSE, bvlc_googlenet/README.md, bvlc_reference_caffenet/LICENSE, bvlc_reference_caffenet/README.md, bvlc_reference_rcnn_ilsvrc13/LICENSE, bvlc_reference_rcnn_ilsvrc13/README.md, densenet121/README.md, inception_v1/README.md, inception_v2/README.md, resnet50/README.md, shufflenet/README.md, squeezenet/README.md, vgg16/README.md, vgg19/README.md
=> Add the details about the models

resnet50/README.md
Addressing the problem here: https://github.com/onnx/models/issues/64
=> Add preprocessing information

bvlc_alexnet/README.md, bvlc_googlenet/README.md, bvlc_reference_caffenet/README.md, bvlc_reference_rcnn_ilsvrc13/README.md, densenet121/README.md, inception_v1/README.md, inception_v2/README.md, resnet50/README.md, shufflenet/README.md, squeezenet/README.md, vgg19/README.md, zfnet512/README.md
Now models are updated to newest opset version.
=> Add opset_7 link

models/semantic_segmentation/DUC/README.md
Adding link in readme for DUC pointing to its model server archive
=> adding DUC model server link

models/image_classification/imagenet_inference.ipynb
Signed-off-by: Bofu Chen (bafu) <bofu@dt42.io>
Update demo code in Inference Demo for ImageNet Models tutorial.
=> Update demo code in Inference Demo for ImageNet Models tutorial.

models/image_classification/imagenet_validation.ipynb
Updated ONNX-MXNet import in imagenet_validation.ipynb acc #97
=> Updated validation notebook for ImageNet models

README.md
Model use cases
Description of model
|Model Name       |ONNX Model download link with size  | MD5 checksum for the ONNX model| tar file containing ONNX model and synthetic test data (in .pb format)|ONNX version used for conversion| Opset version used for conversion|Accuracy values |
```
import onnx
model_proto = onnx.load("path to .onnx file") …
```
=> clarify readme to address #78

emotion_ferplus/README.md, mnist/README.md, resnet50/README.md, squeezenet/README.md
Model use cases
Description of model
|Model Name       |ONNX Model download link with size  | MD5 checksum for the ONNX model| tar file containing ONNX model and synthetic test data (in .pb format)|ONNX version used for conversion| Opset version used for conversion|Accuracy values |
```
import onnx
model_proto = onnx.load("path to .onnx file") …
```
=> Add demo for resnet50, squeezenet, mnist and emotion_ferplus

README.md
- Based on feedback from first time users who had some trouble with finding the usage section
- Edits for minor wording / grammar fixes
=> Restructure README and prioritize usage section

README.md
- grouping logical categories together (in anticipation of more models being added to the model zoo)
i.e. semantic segmentation, object detection and segmentation -> object detection and image segmentation
- adding more detailed descriptions for image classification models
- adding descriptions of new model categories
=> TOC reorganization and additional descriptions for model zoo README

LICENSE
also update formatting so github can autodetect license type
=> update copyright for open governance

contribute.md
Redirect pull request link from deprecated model zoo -> ONNX model zoo in contribution instructions.
=> Update contribution PR link

README.md, bidaf/README.md
This is a patch for existing BiDAF model
=> Address some CR, and use NLTK for word tokenize in preprocess

ssd/README.md
Model use cases
Description of model
|Model Name       |ONNX Model download link with size  | MD5 checksum for the ONNX model| tar file containing ONNX model and synthetic test data (in .pb format)|ONNX version used for conversion| Opset version used for conversion|Accuracy values |
```
import onnx
model_proto = onnx.load("path to .onnx file") …
```
=> Update the pre-processing logic for SSD model

contribute.md
This PR is to correct the link of resent README.
=> correct link

vision/object_detection_segmentation/tiny_yolov3/model/yolov3-tiny.tar.gz
Update test_data for tiny_yolov3
=> Update test_data for tiny_yolov3

vision/classification/shufflenet_v2/README.md
=> fix broken link to model+data package

vision/classification/shufflenet_v2/README.md
Fix broken link for the Shufflenetv2 script
=> Fix broken link in ShuffleNet V2

.lfsconfig, README.md
As title, resolving #215. Addressing #271.
=> Add instructions and default behavior for LFS

README.md
=> Fix typo in git LFS install instructions

vision/body_analysis/arcface/README.md, vision/body_analysis/arcface/model/arcfaceresnet100-opset8-md5.txt, vision/body_analysis/arcface/model/arcfaceresnet100-opset8.onnx, vision/body_analysis/arcface/model/arcfaceresnet100-opset8.tar.gz
=> move arcface model files into git lfs

vision/body_analysis/arcface/dependencies/face_preprocess.py, vision/body_analysis/arcface/dependencies/image_iter.py, vision/body_analysis/arcface/dependencies/verification.py
https://portingguide.readthedocs.io/en/latest/iterators.html#new-behavior-of-range
Model use cases
Description of model
|Model Name       |ONNX Model download link with size  | MD5 checksum for the ONNX model| tar file containing ONNX model and synthetic test data (in .pb format)|ONNX version used for conversion| Opset version used for conversion|Accuracy values |
```
import onnx …
```
=> xrange() was removed in Python 3

vision/object_detection_segmentation/ssd/README.md
Title explains the issue, making link consistent with other READMEs
=> Fixing link in SSD doc

vision/classification/mnist/README.md
=> Update mnist README.md

.github/ISSUE_TEMPLATE/bug_report.md, .github/ISSUE_TEMPLATE/feature_request.md, .github/ISSUE_TEMPLATE/model_request.md, .github/ISSUE_TEMPLATE/question.md
Allow issue templates to be picked up by Github UI. Address wording.
=> Enable Github issue templates

vision/object_detection_segmentation/yolov4/README.md
Link update for Conversion.ipynb
Description of model - What task does it address (i.e. object detection, image classification)? What is the main advantage or feature of this model's architecture?
```
import onnx
model_proto = onnx.load("path to .onnx file")
checker.check_model(model_proto)
```
|Model        |Download  | Download (with sample test data)|ONNX version|Opset version|Accuracy |
|-------------|:--------------|:--------------|:--------------|:--------------|:--------------|
|Model Name       | Relative link to ONNX Model with size  | tar file containing ONNX …
=> YoloV4 - README update

.github/ISSUE_TEMPLATE/feature_request.md, vision/super_resolution/sub_pixel_cnn_2016/model/super-resolution-10.tar.gz
Address #321 for output and input data discrepancies for super resolution model.
=> Fix data for Super Resolution model

vision/classification/inception_and_googlenet/googlenet/README.md
GoogLenet - update of readme, adding pre and post process
=> GoogLenet Pre and post process 

vision/object_detection_segmentation/ssd-mobilenetv1/README.md
=> Fix broken link to SSD MobileNet model file

workflow_scripts/test_models.py
Updated the existing test_models script to use git lfs and added error handling.
This PR does not change the existing script for azure pipelines. It will be deleted along with the azurepipelines yml files
=> adding test script for github actions

vision/classification/efficientnet-lite4/model/efficientnet-lite4-11.tar.gz
- inputs had shapes (224, 224, 3) while model requires (1, 224, 224, 3)
- outputs had only one element (top1) while model returns (1, 1000) tensor
(new outputs were generated using onnxruntime and its top1 matches with the old value)
- change file names in test_data_set_1 and test_data_set_2 directories
Signed-off-by: Mateusz Tabaka <mateusz.tabaka@intel.com>
efficientnet-lite4
Description of model - What task does it address (i.e. object detection, image classification)? What is the main advantage or feature of this model's architecture?
```
import onnx
model_proto = …
```
=> Fix input and output data shapes for efficientnet-lite4

text/machine_comprehension/t5/dependencies/models.py
addressing[ #424](https://github.com/onnx/models/issues/424) issue, 
fixed the bug in GenerativeT5 class of T5 model.
=> Fix bug in T5 model code

vision/classification/onnxrt_inference.ipynb, vision/classification/resnet/model_quantized/README.md
ResNet models perform image classification - they take images as input and classify the major object in the image into a set of pre-defined classes. They are trained on ImageNet dataset which contains images from 1000 classes. ResNet models provide very high accuracies with affordable model sizes. They are ideal for cases when high accuracy of classification is required.
Deeper neural networks are more difficult to train. Residual learning framework ease the training of networks that are substantially deeper. The research explicitly reformulate the layers as learning residual functions with reference to the layer inputs, instead of learning unreferenced functions. It also provide comprehensive empirical evidence showing that these residual networks are easier to optimize, and can gain …
=> Add int8 resnet50 model

ONNX_HUB_MANIFEST.json, README.md, vision/body_analysis/emotion_ferplus/README.md, vision/classification/mnist/README.md, vision/object_detection_segmentation/tiny-yolov2/README.md, workflow_scripts/generate_onnx_hub_manifest.py
First stage of #455 (Onnx hub)
=> Add ONNX Hub Manifest and Generation Code

ONNX_HUB_MANIFEST.json, vision/classification/resnet/README.md, workflow_scripts/generate_onnx_hub_manifest.py
Updating the model hub manifest and adding code to extract feature tensor information. Note that these feature tensors cannot be extracted automatically and required manual curation
=> Update manifest and add feature tensor information

text/machine_comprehension/bert-squad/README.md, text/machine_comprehension/bert-squad/model/bertsquad-12-int8.onnx, text/machine_comprehension/bert-squad/model/bertsquad-12-int8.tar.gz, text/machine_comprehension/bert-squad/model/bertsquad-12.onnx, text/machine_comprehension/bert-squad/model/bertsquad-12.tar.gz
This model answers questions based on the context of the given input paragraph.
BERT (Bidirectional Encoder Representations from Transformers) applies Transformers, a popular attention model, to language modelling. This mechanism has an encoder to read the input text and a decoder that produces a prediction for the task. This model uses the technique of masking out some of the words in the input and then condition each word bidirectionally to predict the masked words. BERT also learns to model relationships between sentences, predicts if the sentences are connected or not.
|Model        |Download  |Download (with sample test data)| ONNX version |Opset version| Accuracy|
| ------------- | ------------- | ------------- | ------------- | ------------- | ------------- |
|BERT-Squad| [416 …
=> add int8 bert model

text/machine_comprehension/bert-squad/README.md, vision/classification/alexnet/README.md, vision/classification/caffenet/README.md, vision/classification/inception_and_googlenet/googlenet/README.md, vision/classification/resnet/README.md, vision/classification/shufflenet/README.md, vision/classification/squeezenet/README.md, vision/classification/vgg/README.md, vision/classification/zfnet-512/README.md
=> update INC link

vision/object_detection_segmentation/fcn/README.md
FCNs are a model for real-time neural network for class-wise image segmentation. As the name implies, every weight layer in the network is convolutional. The final layer has the same height/width as the input image, making FCNs a useful tool for doing dense pixel-wise predictions without a significant amount of postprocessing. Being fully convolutional also provides great flexibility in the resolutions this model can handle.
This specific model detects 20 different [classes](dependencies/voc_classes.txt). The models have been pre-trained on the COCO train2017 dataset on this class subset.
| Model          | Download                              | Download (with sample test data)        | ONNX version | Opset version | Mean IoU |
|----------------|:--------------------------------------|:-- …
=> fix data error

vision/classification/shufflenet/README.md, vision/classification/vgg/model/vgg16-12-int8.tar.gz
add vgg16-12-int8.tar.gz and fix path of shufflenet-v2-12-int8.tar.gz
=> fix file missing

workflow_scripts/test_models.py
**Description**
Fix unintentional change in CI for removing created tar directory
**Motivation**
Bug fix for https://github.com/onnx/models/pull/515.
=> Fix unintentional change in CI for removing created tar directory

vision/classification/alexnet/README.md, vision/classification/caffenet/README.md, vision/classification/densenet-121/README.md, vision/classification/inception_and_googlenet/googlenet/README.md, vision/classification/inception_and_googlenet/inception_v1/README.md, vision/classification/mobilenet/README.md, vision/classification/resnet/README.md, vision/classification/shufflenet/README.md, vision/classification/squeezenet/README.md, vision/classification/vgg/README.md, vision/classification/zfnet-512/README.md, vision/object_detection_segmentation/faster-rcnn/README.md, vision/object_detection_segmentation/ssd/README.md
=> update model link

vision/classification/mnist/README.md, vision/classification/mnist/model/mnist-12-int8.onnx, vision/classification/mnist/model/mnist-12-int8.tar.gz, vision/classification/mnist/model/mnist-12.onnx, vision/classification/mnist/model/mnist-12.tar.gz, vision/object_detection_segmentation/duc/README.md, vision/object_detection_segmentation/duc/model/ResNet101-DUC-12-int8.onnx, vision/object_detection_segmentation/duc/model/ResNet101-DUC-12-int8.tar.gz, vision/object_detection_segmentation/duc/model/ResNet101-DUC-12.onnx, vision/object_detection_segmentation/duc/model/ResNet101-DUC-12.tar.gz
DUC is a semantic segmentation model, i.e., for an input image the model labels each pixel in the image into a set of pre-defined categories. The model provides very good accuracy in terms of [mIOU](#metric) (mean Intersection Over Union) score and can be used in any application requiring semantic segmentation. In particular, since the model is trained on the [cityscapes dataset](#dset) which contains images from urban street scenes, it can be used effectively in self driving vehicle systems.
DUC is a CNN based model for semantic segmentation which uses an image classification network (ResNet) as a backend and achieves improved accuracy in terms of mIOU score using two novel techniques. The first technique is called Dense Upsampling Convolution (DUC) which generates pixel-level prediction …
=> add int8 mnist & resnet-duc

ONNX_HUB_MANIFEST.json, vision/classification/shufflenet/model/shufflenet-6.onnx, vision/classification/shufflenet/model/shufflenet-6.tar.gz, vision/classification/shufflenet/model/shufflenet-8.onnx, vision/classification/shufflenet/model/shufflenet-8.tar.gz
- To Correct models, swap suffleneet-6 and shufflenet-8.
- Fixes https://github.com/onnx/models/issues/559.
=> Correct models: swap suffleneet-6 and shufflenet-8

.github/workflows/codeql.yml
Create codeql.yml to replace depreacted LGTM.com
=> Create codeql.yml to replace depreacted LGTM.com

README.md
fixed links in the README.md file:
- models zoo website
- TurnkeyML website
- contribution guidelines
=> Updated README.md - fixed broken links

ONNX_HUB_MANIFEST.json
This PR updates the onnx hub manifest to account for renaming of the `archive` to `validated`.
=> Update hub manifest

index.html
This pull request includes a change to the `index.html` file. The change involves adding Google Tag Manager (gtag.js) to the file for tracking and analytics purposes. The Google Tag Manager script is added in the head section of the HTML document and is configured with a specific ID. This will allow for better tracking of user interactions and analytics on the website.
=> Adding google analytics tag
