onnx/models

- README.md
This is useful for selecting e.g. the smallest file when one wants to download one of the model files for a test.
> added image file sizes (as reported by wget --spider) to README.md

- README.md
- bvlc_googlenet/README.md
- bvlc_reference_caffenet/README.md
- bvlc_reference_rcnn_ilsvrc13/README.md
All converted from Caffe2 model zoo.
1) bvlc_googlenet
2) bvlc_reference_caffenet
3) bvlc_reference_rcnn_ilsvrc13
All passed the end to end tests.
> Add three models to onnx model zoo

- README.md
- zfnet512/README.md
ZFNet-512 is more precise since the model is slightly different from the original one.
> Rename ZFNet to ZFNet-512

- resnet50/README.md
*resnet50_trainer.py* is not hosted in Azure BatchAI repo anymore, it lives in Caffe2 folder in PyTorch.
> Update resnet50_trainer URL

- README.md
- ssd/README.md
This model is a real-time neural network for object detection that detects 80 different classes.
|SSD       |[80.4 MB](https://onnxzoo.blob.core.windows.net/models/opset_10/ssd/ssd.onnx) | [MD5](https://onnxzoo.blob.core.windows.net/models/opset_10/ssd/ssd-md5.txt) | [78.5 MB](https://onnxzoo.blob.core.windows.net/models/opset_10/ssd/ssd.tar.gz) |1.4.1 |10 |mAP of 0.195 |
<hr>
Image shape `(1x3x1200x1200)`
The images have to be loaded in to a range of [0, 1], resized to (1200, 1200) with bilinear interpolation and then normalized using mean = [0.485, 0.456, 0.406] and std = …
> Single Stage Detector

- bvlc_googlenet/README.md
The output name of googlenet is prob_0 instead of softmaxout_1
> Fix wrong output name of googlenet

- README.md
- yolov3/README.md
This model is a neural network for real-time object detection that detects 80 different classes. It is very fast and accurate.
|Model        |Download  |Checksum|Download (with sample test data)|ONNX version|Opset version|Accuracy |
|YOLOv3       |[237 MB](https://onnxzoo.blob.core.windows.net/models/opset_10/yolov3/yolov3.onnx) | [MD5](https://onnxzoo.blob.core.windows.net/models/opset_10/yolov3/yolov3-md5.txt) |[222 MB](https://onnxzoo.blob.core.windows.net/models/opset_10/yolov3/yolov3.tar.gz)|1.5 |10 |mAP of 0.553 |
<hr>
Resized image `(1x3x416x416)`
Original image size `(1x2)` which is `[image.size[1], image.size[0]]` 
The images have to be loaded in to a range of [0, 1]. …
> Add yolov3 model

- README.md
- bidaf/README.md
This model is a neural network for answering a query about a given context paragraph.
|Model        |Download  |Checksum|Download (with sample test data)|ONNX version|Opset version|Accuracy |
|BiDAF  |[41.5 MB](https://onnxzoo.blob.core.windows.net/models/opset_9/bidaf/bidaf.onnx) | [MD5](https://onnxzoo.blob.core.windows.net/models/opset_9/bidaf/bidaf-md5.txt) |[37.3 MB](https://onnxzoo.blob.core.windows.net/models/opset_9/bidaf/bidaf.tar.gz)|1.5 |9 |EM of 68.1 in SQuAD v1.1 |
<hr>
Tokenized strings of context paragraph and query.
Tokenize words and chars in string for context and query. The tokenized words are in lower case, while chars are not. Chars of each word needs to be …
> Add BiDAF model

- ssd/README.md
In the SSD model readme, the first link in the reference section was broken. I found the correct link and updated the readme.
> fixed broken link in reference section of the ssd readme

- vision/classification/resnet/README.md
- vision/classification/resnet/model/resnet101-v1.onnx
- vision/classification/resnet/model/resnet101-v1.tar.gz
- vision/classification/resnet/model/resnet101-v2.onnx
- vision/classification/resnet/model/resnet101-v2.tar.gz
- vision/classification/resnet/model/resnet152-v1.onnx
- vision/classification/resnet/model/resnet152-v1.tar.gz
- vision/classification/resnet/model/resnet152-v2.onnx
- vision/classification/resnet/model/resnet152-v2.tar.gz
- vision/classification/resnet/model/resnet18-v1.onnx
- vision/classification/resnet/model/resnet18-v1.tar.gz
- vision/classification/resnet/model/resnet18-v2.onnx
- vision/classification/resnet/model/resnet18-v2.tar.gz
- vision/classification/resnet/model/resnet34-v1.onnx
- vision/classification/resnet/model/resnet34-v1.tar.gz
- vision/classification/resnet/model/resnet34-v2.onnx
- vision/classification/resnet/model/resnet34-v2.tar.gz
- vision/classification/resnet/model/resnet50-v1.onnx
- vision/classification/resnet/model/resnet50-v1.tar.gz
- vision/classification/resnet/model/resnet50-v2.onnx
- vision/classification/resnet/model/resnet50-v2.tar.gz
- vision/classification/resnet/resnet50-caffe2/README.md
Git LFS (#271) for ResNet v1 and v2. Regenerate models from mxnet exporter to fix batch normalization spatial export bug (labeled as 0 when 1 is required)
apache/incubator-mxnet#17711
> ResNet: GitLFS, MxNet batch normalization bug fix for spatial export

- vision/classification/resnet/README.md
Fixing tables in ResNet README -- making the distinction between ResNet v1 and ResNet v2 clearer.
> Minor update to ResNet README

- vision/object_detection_segmentation/tiny-yolov2/README.md
- vision/object_detection_segmentation/tiny-yolov2/model/tinyyolov2-1.onnx
- vision/object_detection_segmentation/tiny-yolov2/model/tinyyolov2-1.tar.gz
- vision/object_detection_segmentation/tiny-yolov2/model/tinyyolov2-7.onnx
- vision/object_detection_segmentation/tiny-yolov2/model/tinyyolov2-7.tar.gz
- vision/object_detection_segmentation/tiny-yolov2/model/tinyyolov2-8.onnx
- vision/object_detection_segmentation/tiny-yolov2/model/tinyyolov2-8.tar.gz
#271 
TinyYoloV2 migration to Git LFS, deprecating checksums.
> TinyYoloV2 - Git LFS migration

- vision/classification/squeezenet/model/squeezenet1.1-7.onnx
Squeezenet 1.1 upload has a protobuf parsing error. Updated with a working version based on the original submitter's link. Likely was a git LFS upload error.
> Fixing Squeezenet 1.1 opset 7 model

- text/machine_comprehension/gpt-2/README.md
- text/machine_comprehension/gpt-2/dependencies/GPT2-export.py
- text/machine_comprehension/gpt-2/model/gpt2-lm-head-10.onnx
- text/machine_comprehension/gpt-2/model/gpt2-lm-head-10.tar.gz
When we use the GPT-2 onnx model, we want to generate new words by it. However, the current GPT-2 model only gives the last hidden states, rather than the next word's prediction.
So based on the previous work, this PR tries to add GPT2LMHeadModel, including editing the export script and postprocessing code.
> Adding GPT-2-LH-Model model

- .github/workflows/linux_ci.yml
- .github/workflows/windows_ci.yml
This is Part 1 PR for moving CIs to github actions.
Part 1 - Add github actions for CI
Part 2- Thoroughly test github actions and deprecate azure pipelines
> move CI to github actions

- vision/object_detection_segmentation/tiny-yolov3/README.md
tiny-yolov3
The post processing step documented for tiny yolov3 does not work out of the box. The `indices` from the inference output is of a different shape, and the for .. in loop crashes due to it. 
It has been corrected by replacing `for idx_ in indices:` to `for idx_ in indices[0]:`.
This fix is inspired from the test case [here](https://github.com/onnx/keras-onnx/blob/master/applications/nightly_build/test_yolov3.py#L42).
> Fixed documentation for tiny-yolov3 post processing

- vision/object_detection_segmentation/yolov4/model/yolov4.tar.gz
Seems like the outputs were the copies of the inputs.
New outputs are generated with onnxruntime and grouped in test_data_set_* directories.
Signed-off-by: Mateusz Tabaka <mateusz.tabaka@intel.com>
> Fix output tensors in Yolo v4 model

- vision/classification/shufflenet/ShufflenetV2-export.py
enable export of Shufflenet with dynamic axes
PR https://github.com/pytorch/vision/pull/3158 fixes Shufflenet model, so it can be exported with dynamic axes
> [ONNX] enable export of Shufflenet with dynamic axes

- workflow_scripts/check_model.py
**Description**
Skip ORT backend test if the model has opset<7.
**Motivation**
ONNXRuntime only *guarantees* support for models stamped with opset version 7.
Unblock this PR https://github.com/onnx/models/pull/411 by skipping the inexecutable test.
> Skip ORT backend test if the model has opset<7

- vision/classification/mnist/model/mnist-1.onnx
- vision/classification/mnist/model/mnist-1.tar.gz
This is how the model was changed:
```
-- model.prototxt.orig 2020-12-22 12:16:40.634961643 +0100
+++ model.prototxt      2020-12-22 12:18:40.589855609 +0100
@@ -6409,21 +6409,8 @@
domain: ""
}
node {
-    input: "Constant367"
-    output: "Reshape420_Output_0"
-    name: "Reshape420"
-    op_type: "Reshape"
-    attribute {
-      name: "shape"
-      ints: 10
-      type: INTS
-    }
-    doc_string: ""
-    domain: ""
-  }
-  node {
input: "Times418_Output_0"
-    input: "Reshape420_Output_0"
+    input: "Constant367"
output: "Plus422_Output_0"
name: "Plus214"
op_type: "Add"
```
The unnecessary node did reshape of Constant367 (which has shape [1, 10]) to shape [10],
and the output of that operation was passed as a second input to Add node (named "Plus214").
Since first input to …
> Remove unnecessary reshape in mnist-1 model

- contribute.md
Fix the broken url in contribute.md: use `.github/PULL_REQUEST_TEMPLATE.md` instead of `PULL_REQUEST_TEMPLATE` because the document has been moved.
> Fix the broken url in contribute.md

- text/machine_comprehension/bert-squad/model/bertsquad-10.tar.gz
Fixing expected result merged in https://github.com/onnx/models/pull/418 was fine but I've observed another problems:
1. Outputs in Bertsquad-10 ONNX model are in order:
- `unstack:1`
- `unstack:0`
- `unique_ids:0`
but expected outputs are saved as:
output_0.pb -> `unique_ids:0`
output_1.pb -> `unstack:0`
output_2.pb -> `unstack:1`
The order was fixed.
2. The second minor thing was incorrect folder name: `download_sample_10` after unpacking `bertsquad-10.tar.gz`.
It was changed to `bertsquad-10`.
> Change BertSquad-10 expected results order

- vision/classification/mobilenet/model/mobilenetv2-7.tar.gz
- vision/classification/mobilenet/model/mobilnetv2-7.tar.gz
After merge https://github.com/onnx/models/pull/410 there are missing test data to Mobilenetv2 in `mobilnetv2-7.tar.gz`
I used inputs from version before #410 update and generate outputs using onnx runtime (1.6.0) on current version of model.
(minor - The name of package was changed to `mobilenetv2-7.tar.gz`)
> [Mobilenetv2] Add missing test data

- README.md
Link to `Language Modelling` in TOC jump to `Language` sub-section in `Model` section, but it should jump to `Language Modelling` section.
> Fix internal link in README

- text/machine_comprehension/gpt2-bs/README.md
- text/machine_comprehension/gpt2-bs/model/gpt2-lm-head-bs-12.onnx
Transformer-based language model for text generation.
This GPT-2 model with generation can produce the result without any extra code or algorithm. It already embedded a beam search algorithm into the ONNX model, so there is **NO** Post-Processing code to inference.
|Model        |Download  | Compressed |ONNX version|Opset version|
|-------------|:--------------|:--------------|:--------------|:--------------|
|gpt2-lm-head-bs |[635 MB](model/gpt2-lm-head-bs-12.onnx) | N/A (similiar size) | 1.7 | 12
Huggingface PyTorch GPT-2-with-lm-head + conversion script ==> ONNX GPT-2-LM-HEAD-BS.onnx
The full conversion script is in [onnxruntime-extentions](https://github.com/microsoft/onnxruntime-extensions/blob/main/tutorials/gpt2bs.py), and some model parameters can be changed if the number in the …
> A GPT-2 model with Beam Search Generation

- vision/classification/efficientnet-lite4/README.md
- vision/classification/efficientnet-lite4/model/efficientnet-lite4-11-int8.onnx
- vision/classification/efficientnet-lite4/model/efficientnet-lite4-11-int8.tar.gz
- vision/classification/inception_and_googlenet/inception_v1/README.md
- vision/classification/inception_and_googlenet/inception_v1/model/inception-v1-12-int8.onnx
- vision/classification/inception_and_googlenet/inception_v1/model/inception-v1-12-int8.tar.gz
- vision/classification/inception_and_googlenet/inception_v1/model/inception-v1-12.onnx
- vision/classification/inception_and_googlenet/inception_v1/model/inception-v1-12.tar.gz
- vision/object_detection_segmentation/fcn/README.md
- vision/object_detection_segmentation/fcn/model/fcn-resnet50-12-int8.onnx
- vision/object_detection_segmentation/fcn/model/fcn-resnet50-12-int8.tar.gz
- vision/object_detection_segmentation/fcn/model/fcn-resnet50-12.onnx
- vision/object_detection_segmentation/fcn/model/fcn-resnet50-12.tar.gz
- vision/object_detection_segmentation/ssd-mobilenetv1/README.md
- vision/object_detection_segmentation/ssd-mobilenetv1/model/ssd_mobilenet_v1_12-int8.onnx
- vision/object_detection_segmentation/ssd-mobilenetv1/model/ssd_mobilenet_v1_12-int8.tar.gz
- vision/object_detection_segmentation/ssd-mobilenetv1/model/ssd_mobilenet_v1_12.onnx
- vision/object_detection_segmentation/ssd-mobilenetv1/model/ssd_mobilenet_v1_12.tar.gz
- vision/object_detection_segmentation/ssd/README.md
- vision/object_detection_segmentation/ssd/model/ssd-12-int8.onnx
- vision/object_detection_segmentation/ssd/model/ssd-12-int8.tar.gz
- vision/object_detection_segmentation/ssd/model/ssd-12.onnx
- vision/object_detection_segmentation/ssd/model/ssd-12.tar.gz
EfficientNet-Lite4 is an image classification model that achieves state-of-the-art accuracy. It is designed to run on mobile CPU, GPU, and EdgeTPU devices, allowing for applications on mobile and loT, where computational resources are limited.
EfficientNet-Lite 4 is the largest variant and most accurate of the set of EfficientNet-Lite model. It is an integer-only quantized model that produces the highest accuracy of all of the EfficientNet models. It achieves 80.4% ImageNet top-1 accuracy, while still running in real-time (e.g. 30ms/image) on a Pixel 4 CPU.
|Model        |Download | Download (with sample test data)|ONNX version|Opset version|Top-1 accuracy (%)|
|-------------|:--------------|:--------------|:--------------|:--------------|:--------------|
|EfficientNet-Lite4     | [51.9 …
> add int8 efficientnet, inceptionv1, ssdmbv1, ssd, fcn_rn50

- .github/workflows/linux_ci.yml
- workflow_scripts/test_models.py
**Description**
Recently onnx/models has changed its default branch to main branch: https://github.com/onnx/models/pull/497. We should also use main branch in the code to prevent issues.
**Motivation**
Currently ONNX/ORT check is not working in CIs
> Fix idle ONNX/ORT check in CIs: use main branch instead

- ONNX_HUB_MANIFEST.json
- vision/classification/imagenet_preprocess.py
- vision/classification/resnet/README.md
- vision/classification/resnet/preproc/resnet-preproc-v1-18.onnx
- vision/classification/resnet/preproc/resnet-preproc-v1-18.tar.gz
- workflow_scripts/generate_onnx_hub_manifest.py
- workflow_scripts/onnx_test_data_utils.py
- workflow_scripts/ort_test_dir_utils.py
It modifies ResNet page to use ONNX for the data preprocessing steps. This is the result of the work from the ONNX preprocessing working-group (see https://github.com/onnx/working-groups/tree/main/preprocessing)
|Model        |Download  | Download (with sample test data)|ONNX version|Opset version|Accuracy |
|-------------|:--------------|:--------------|:--------------|:--------------|:--------------|
|ResNet-preproc| [4.0KB](preproc/resnet-preproc-v1-18.onnx)  |  [864 KB](preproc/resnet-preproc-v1-18.tar.gz) |  1.13.1 | 18| N/A|
Created via ONNX parser. See details here: https://github.com/onnx/working-groups/blob/main/preprocessing/notebooks/resnet_preproc_zoo/Resnet%20preprocessing%20model%20and%20data%20preparation.ipynb
See …
> Add ResNet preprocessing model
